name: Embold Code Quality Scan

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  embold-scan_fc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Download and extract the Embold scanner
      - name: Download and Extract Scanner
        run: |
          curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      # Step 3: Download the repository configuration file
      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET \
            "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/fc546d94098788f6198dd483b2623b93/scans/config/download" \
            --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" \
            -o repository-configuration.json

      # Step 4: Run the Embold analysis scanner
      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_TOKEN_JAVA }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t $EMBOLD_TOKEN \
            -r fc546d94098788f6198dd483b2623b93 \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home \
            -v
